INSERT INTO corsi (descrizione) values ('Orientamento propedeutico');
INSERT INTO corsi (descrizione) values ('Materiale condiviso - Cartella del partecipante');
INSERT INTO corsi (descrizione) values ('Materiale condiviso - Docenti');
INSERT INTO corsi (descrizione) values ('Approfondimenti didattici');
INSERT INTO corsi (descrizione) values ('Autenticazione, Autorizzazione e firme digitali');
INSERT INTO corsi (descrizione) values ('Base di dati - NoSQL');
INSERT INTO corsi (descrizione) values ('Base di dati - SQL');
INSERT INTO corsi (descrizione) values ('AI e Machine Learning - Python');
INSERT INTO corsi (descrizione) values ('Business Intelligence');
INSERT INTO corsi (descrizione) values ('Cloud Services e Container');
INSERT INTO corsi (descrizione) values ('Concetti di Economia e Finanza Decentralizzata');
INSERT INTO corsi (descrizione) values ('Copyright e norme giuridiche del mondo digitale');
INSERT INTO corsi (descrizione) values ('Fondamenti AGILE');
INSERT INTO corsi (descrizione) values ('Fondamenti di basi di dati');
INSERT INTO corsi (descrizione) values ('Fondamenti di programmazione');
INSERT INTO corsi (descrizione) values ('Fondamenti di reti di calcolatori');
INSERT INTO corsi (descrizione) values ('Fondamenti di Version Control');
INSERT INTO corsi (descrizione) values ('Inglese');
INSERT INTO corsi (descrizione) values ('Laboratorio di preparazione project work');
INSERT INTO corsi (descrizione) values ('Learning by Project');
INSERT INTO corsi (descrizione) values ('Linux Server');
INSERT INTO corsi (descrizione) values ('Orientamento');
INSERT INTO corsi (descrizione) values ('Parità fra uomini e donne e non discriminazione');
INSERT INTO corsi (descrizione) values ('Percorso di svilupo Soft-Skills');
INSERT INTO corsi (descrizione) values ('Programmazione - Java');
INSERT INTO corsi (descrizione) values ('Programmazione WEB - HTML | CSS | Javascript');
INSERT INTO corsi (descrizione) values ('RESTful API');
INSERT INTO corsi (descrizione) values ('Sicurezza sul lavoro');
INSERT INTO corsi (descrizione) values ('Tecnologie Blockchain');